export default [
  { name: "Alice Johnson", age: 25, is_active: true, birth_date: new Date("1999-03-12"), interests: ["reading", "traveling", "music"] },
  { name: "Bob Smith", age: 34, is_active: false, birth_date: new Date("1990-07-25"), interests: ["sports", "cooking", "gaming"] },
  { name: "Charlie Brown", age: 28, is_active: true, birth_date: new Date("1996-05-14"), interests: ["hiking", "movies", "technology"] },
  { name: "Diana White", age: 22, is_active: false, birth_date: new Date("2002-01-30"), interests: ["fashion", "photography", "dancing"] },
  { name: "Edward Black", age: 41, is_active: true, birth_date: new Date("1983-10-08"), interests: ["traveling", "history", "wine tasting"] },
  { name: "Fiona Green", age: 31, is_active: false, birth_date: new Date("1993-12-19"), interests: ["yoga", "art", "gardening"] },
  { name: "George Harris", age: 27, is_active: true, birth_date: new Date("1997-06-07"), interests: ["cycling", "sports", "writing"] },
  { name: "Helen Moore", age: 36, is_active: false, birth_date: new Date("1988-09-14"), interests: ["cooking", "traveling", "volunteering"] },
  { name: "Ian Wilson", age: 29, is_active: true, birth_date: new Date("1995-02-03"), interests: ["gaming", "movies", "technology"] },
  { name: "Julia Adams", age: 40, is_active: false, birth_date: new Date("1984-08-21"), interests: ["reading", "music", "theater"] },
  { name: "Kevin Brown", age: 33, is_active: true, birth_date: new Date("1991-11-11"), interests: ["fishing", "sports", "traveling"] },
  { name: "Laura Scott", age: 26, is_active: false, birth_date: new Date("1998-04-15"), interests: ["fashion", "photography", "dancing"] },
  { name: "Michael King", age: 45, is_active: true, birth_date: new Date("1979-07-28"), interests: ["history", "wine tasting", "golf"] },
  { name: "Nina Carter", age: 24, is_active: false, birth_date: new Date("2000-06-09"), interests: ["yoga", "meditation", "traveling"] },
  { name: "Oliver Reed", age: 38, is_active: true, birth_date: new Date("1986-03-22"), interests: ["sports", "movies", "photography"] },
  { name: "Paula Young", age: 30, is_active: false, birth_date: new Date("1994-10-05"), interests: ["hiking", "writing", "board games"] },
  { name: "Quentin Lewis", age: 32, is_active: true, birth_date: new Date("1992-09-12"), interests: ["reading", "cooking", "gaming"] },
  { name: "Rachel Hall", age: 27, is_active: false, birth_date: new Date("1997-11-23"), interests: ["fashion", "blogging", "movies"] },
  { name: "Samuel Evans", age: 39, is_active: true, birth_date: new Date("1985-12-17"), interests: ["golf", "technology", "traveling"] },
  { name: "Tina Clark", age: 23, is_active: false, birth_date: new Date("2001-05-29"), interests: ["dancing", "music", "art"] },
];